### ISSUE TITLE
Disable overrides not working

### ISSUE THREAD

**Issue by okadots** [khromov/acf-local-json-manager#5]
Hi! Thanks for this plugin! It's helping me greatly :)

When I try to "disable overrides" and save other fields, the json files do not appear or update in the default location.

**Comment by khromov** [comment]
Hey @okadots !

What version of ACF are you using, and are you using the free or PRO version?

**Comment by okadots** [comment]
(hey!! that was so fast!! 💯 )

I'm using ACF Pro 5.8.0-beta3 with Wordpress 5.0. 

I realize you probably haven't had a chance to do testing with the latest beta, but we are working on building our own acf blocks that are dropped into a theme complete with their acf json files. So far, I have that working perfectly. 

Just running into an issue with the json files that are not part of a block (like global settings type stuff)

**Comment by khromov** [comment]
Hey @okadots 

I'll try to check it on that version. Have you tried disabling the plugin to rule out that there isn't a bug in ACF? Things move fast with the betas and Gutenberg support.

If you want to debug a little yourself, basically the plugin itself hooks on the `acf/settings/save_json` filter and chooses between all the registered plugins. But if you disable it via the admin menu it's not supposed to do anything, which you can verify by checking that `$override_plugin` is falsy here: https://github.com/khromov/acf-local-json-manager/blob/master/acf-local-json-manager.php#L179

**Comment by okadots** [comment]
I will give that a try and report back.  Thanks @khromov!

**Comment by okadots** [comment]
@khromov well this was totally a stupid mistake on my part! i had the wrong path for the acf sync for the default stuff. all set now! thanks for your help!
